# Generated by Django 2.2.7 on 2019-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude')),
                ('unique_squirrel_id', models.CharField(help_text='Unique_Squirrel_ID', max_length=20)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM'), ('', '---')], default='other', max_length=10)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '---'), ('', '---')], default='other', max_length=10)),
                ('primary_fur_color', models.CharField(choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), ('', '---')], default='other', max_length=20)),
                ('location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '---')], default='other', max_length=20)),
                ('specific_location', models.CharField(blank=True, help_text='Specific location', max_length=100)),
                ('running', models.BooleanField(default=False, help_text='Running')),
                ('chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('eating', models.BooleanField(default=False, help_text='Eating')),
                ('foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('other_activities', models.CharField(blank=True, help_text='Other Activities', max_length=100)),
                ('kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('moans', models.BooleanField(default=False, help_text='Moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Tail_flags')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Tail_twitches')),
                ('approaches', models.BooleanField(default=False, help_text='Approach')),
                ('indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('runs_from', models.BooleanField(default=False, help_text='Runs from')),
            ],
        ),
    ]
