# Generated by Django 2.2.7 on 2019-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirreltracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '---'), ('', '---')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '---')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='primary_fur_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), ('', '---')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM'), ('', '---')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique_Squirrel_ID', max_length=20, unique=True),
        ),
    ]
